# Generated by Django 5.1.7 on 2025-03-24 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='folloing',
            new_name='following',
        ),
    ]
